version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: reddish
      MONGO_INITDB_ROOT_PASSWORD: reddish
      MONGO_INITDB_ROOT_USERNAME: root

  reddishserver:
    image: 'reddishserver'
    build: ./server
    restart: always
    ports:
      - 3005:3005
    environment:
      MONGODB_URI: 
      OPENAI_API_KEY: 
      CLOUDINARY_CLOUD_NAME: 
      CLOUDINARY_API_KEY: 
      CLOUDINARY_API_SECRET: 

  reddishclient:
    image: 'reddishclient'
    build: ./client
    restart: always
    ports:
      - 80:80
    depends_on:
      - reddishserver
