apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: reddishserver
  name: reddishserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reddishserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/reddish-default: "true"
        io.kompose.service: reddishserver
    spec:
      containers:
        - image: reddishserver
          name: reddishserver
          ports:
            - containerPort: 3005
              hostPort: 3005
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
